---
title: "STR panel overview statistics"
author: "Max Verbiest"
date: '2022-04-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libs}
library(tidyverse)
source("scripts/analyse_variation/str_gt_utils.R")
```

```{r}
df_str_info <- read.csv("/Users/maxverbiest/PhD/data/str_panels/tral_and_perf_panel_meta_info.tsv", header=T, sep="\t")
```

```{r}
df_str_info <- df_str_info %>% 
  mutate(pass_krait = case_when(
    period == 1 & ref >= 14 ~ TRUE,
    period == 2 & ref >= 7 ~ TRUE,
    period == 3 & ref >= 5 ~ TRUE,
    period == 4 & ref >= 4 ~ TRUE,
    period == 5 & ref >= 4 ~ TRUE,
    period == 6 & ref >= 4 ~ TRUE,
    TRUE ~ FALSE
  ))
```


```{r}
# "intron/intergenic" "CDS" "UTR"
df_str_info %>% 
  filter(region_type == "CDS", pass_krait) %>%
  group_by(period) %>% 
  summarize(count = n()) %>% 
  ggplot(aes(x="", y=count, fill=as.factor(period))) +
  geom_col(col="black") +
  coord_polar(theta = "y") +
  theme_void()
  
df_str_info %>% 
  filter(pass_krait) %>% 
  group_by(region_type, period) %>%
  count()
```

```{r}
df_str_info %>% 
  filter(!in_segdup) %>% 
  group_by(region_type, period) %>% 
  summarize(count = n()) %>% View()
```

