---
title: "patient_population"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(TCGAbiolinks)
```

```{r load coad data}
query_coad = GDCquery(project = "TCGA-COAD", 
                 data.category = "Clinical", 
                 file.type = "xml")
GDCdownload(query_coad)
clinical_coad <- GDCprepare_clinic(query_coad,"patient")
clinical_coad[clinical_coad == ""] <- NA
```
```{r load read data}
query_read = GDCquery(project = "TCGA-READ", 
                 data.category = "Clinical", 
                 file.type = "xml")
GDCdownload(query_read)

clinical_read <- GDCprepare_clinic(query_read,"patient")
clinical_read[clinical_read == ""] <- NA
clinical_coad_read <- rbind(clinical_coad, clinical_read)
```


```{r}
clinical_coad_read %>% group_by(race_list) %>% 
  ggplot(aes(x=race_list, fill=project)) +
  geom_bar(position = "dodge") +
  facet_wrap("project") +
  theme(axis.text.x = element_text(angle=45, hjust = 1))
```


```{r}
clinical_coad_read %>% group_by(project, ethnicity) %>% summarize(count=n()) %>% mutate(frac = count/sum(count)) %>%
  ggplot(aes(x=ethnicity, y=frac*100, fill=project)) +
  geom_bar(stat = "identity") +
  facet_wrap("project") +
  theme(axis.text.x = element_text(angle=45, hjust = 1))
```




